name: ciPatrik

on:
  push:
    branches:
      - main

  pull_request:

jobs:
# Todo Matrix hÃ¤r.. typ {{ Matrix }}
  run_tests:
  #fÃ¶r fler os
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet: [9.0, 8.0]
    #runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Build
        run: dotnet build

      #- name: Run Tests
        #run: dotnet test
          echo "" >> $GITHUB_STEP_SUMMARY
      
          echo "## ðŸ§® Total Tests Across All Projects" >> $GITHUB_STEP_SUMMARY
          echo "**$total_tests** tests executed ðŸŽ‰ðŸš€ðŸ”¥" >> $GITHUB_STEP_SUMMARY
