name: ciPatrik

on:
  workflow_dispatch:
  #push:
    #branches:
      #- main

  pull_request:

jobs:
# Todo Matrix h√§r.. typ {{ Matrix }}
  run_tests:
  #f√∂r fler os
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet: [9.0, 8.0]
    #runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Build
        run: dotnet build

      #- name: Run Tests
        #run: dotnet test

      - name: Send to Discord
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOKHILDEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.head_ref || github.ref_name }}
          ACTOR: ${{ github.actor }}
        run: |
          CONTENT="üíÅ Workflow k√∂rdes av ${ACTOR} i ${REPO} p√• branch ${BRANCH}"
          PAYLOAD="{\"username\":\"GitHub Actions\",\"content\":\"${CONTENT}\"}"
          curl -H "Content-Type: application/json" \
               -d "$PAYLOAD" \
               "$WEBHOOK_URL"
