name: ciPatrik

on:
  push:
    branches:
      - main

  pull_request:

jobs:
# Todo Matrix här.. typ {{ Matrix }}
  run_tests:
  #för fler os
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [9.0, 8.0]
    #runs-on: ubuntu-latest

    steps:
      - name: Setup .NET
        uses: action/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.version }}

      - name: Build
        run: dotnet build

      - name: Run Tests
        run: dotnet test
          


  
