name: Github contexts
on:
    push: #push to any branch

jobs:
    print_context_values:

        runs-on: ubuntu-latest

        steps:
            - run: echo ${{ github }}
            - run: echo ${{ runner }}

